# Generated by Django 5.0 on 2025-12-17 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_submissions", models.IntegerField(default=0)),
                ("fake_news_detected", models.IntegerField(default=0)),
                ("real_news_detected", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("avg_confidence_score", models.FloatField(default=0.0)),
                ("total_feedbacks", models.IntegerField(default=0)),
                ("total_reports", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "system_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("verification_complete", "Verification Complete"),
                            ("trending_fake_news", "Trending Fake News"),
                            ("system_alert", "System Alert"),
                            ("feedback_response", "Feedback Response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
