# Generated by Django 5.0 on 2025-12-17 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_name", models.CharField(max_length=100, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("logistic_regression", "Logistic Regression"),
                            ("random_forest", "Random Forest"),
                            ("naive_bayes", "Naive Bayes"),
                            ("bert", "BERT Transformer"),
                            ("lstm", "LSTM Neural Network"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_file", models.FileField(upload_to="ml_models/")),
                (
                    "vectorizer_file",
                    models.FileField(blank=True, null=True, upload_to="ml_models/"),
                ),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("training_dataset_size", models.IntegerField()),
                ("training_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ml_model_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("article", "Full Article"),
                            ("url", "URL"),
                            ("text", "Text Content"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "prediction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fake", "Fake News"),
                            ("real", "Real News"),
                            ("uncertain", "Uncertain"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("fake_probability", models.FloatField(blank=True, null=True)),
                ("real_probability", models.FloatField(blank=True, null=True)),
                ("flagged_keywords", models.JSONField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                (
                    "source_credibility",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("admin_reviewed", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="news_submis_created_c8d1e7_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="news_submis_user_id_cc8a2d_idx",
                    ),
                    models.Index(
                        fields=["prediction"], name="news_submis_predict_ffc8f4_idx"
                    ),
                ],
            },
        ),
    ]
